#informations de base de l'app,
#version, dépendance et éléments utilisés

name: namer_app
description: A new Flutter project.

publish_to : 'none' #Asorina ity ligne ity raha ohatra ka tiana ho 
#publiéna ao am pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk : flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true